/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPredictionRouteImport } from './routes/dashboard.prediction'
import { Route as DashboardMonitoringRouteImport } from './routes/dashboard.monitoring'
import { Route as DashboardMlopsRouteImport } from './routes/dashboard.mlops'
import { Route as DashboardGeoRouteImport } from './routes/dashboard.geo'
import { Route as DashboardFeaturesRouteImport } from './routes/dashboard.features'
import { Route as DashboardDetectionRouteImport } from './routes/dashboard.detection'
import { Route as DashboardCaptureRouteImport } from './routes/dashboard.capture'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPredictionRoute = DashboardPredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitoringRoute = DashboardMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMlopsRoute = DashboardMlopsRouteImport.update({
  id: '/mlops',
  path: '/mlops',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGeoRoute = DashboardGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeaturesRoute = DashboardFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDetectionRoute = DashboardDetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCaptureRoute = DashboardCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/capture': typeof DashboardCaptureRoute
  '/dashboard/detection': typeof DashboardDetectionRoute
  '/dashboard/features': typeof DashboardFeaturesRoute
  '/dashboard/geo': typeof DashboardGeoRoute
  '/dashboard/mlops': typeof DashboardMlopsRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/prediction': typeof DashboardPredictionRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/capture': typeof DashboardCaptureRoute
  '/dashboard/detection': typeof DashboardDetectionRoute
  '/dashboard/features': typeof DashboardFeaturesRoute
  '/dashboard/geo': typeof DashboardGeoRoute
  '/dashboard/mlops': typeof DashboardMlopsRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/prediction': typeof DashboardPredictionRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/capture': typeof DashboardCaptureRoute
  '/dashboard/detection': typeof DashboardDetectionRoute
  '/dashboard/features': typeof DashboardFeaturesRoute
  '/dashboard/geo': typeof DashboardGeoRoute
  '/dashboard/mlops': typeof DashboardMlopsRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/prediction': typeof DashboardPredictionRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/capture'
    | '/dashboard/detection'
    | '/dashboard/features'
    | '/dashboard/geo'
    | '/dashboard/mlops'
    | '/dashboard/monitoring'
    | '/dashboard/prediction'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/capture'
    | '/dashboard/detection'
    | '/dashboard/features'
    | '/dashboard/geo'
    | '/dashboard/mlops'
    | '/dashboard/monitoring'
    | '/dashboard/prediction'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/capture'
    | '/dashboard/detection'
    | '/dashboard/features'
    | '/dashboard/geo'
    | '/dashboard/mlops'
    | '/dashboard/monitoring'
    | '/dashboard/prediction'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prediction': {
      id: '/dashboard/prediction'
      path: '/prediction'
      fullPath: '/dashboard/prediction'
      preLoaderRoute: typeof DashboardPredictionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitoring': {
      id: '/dashboard/monitoring'
      path: '/monitoring'
      fullPath: '/dashboard/monitoring'
      preLoaderRoute: typeof DashboardMonitoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mlops': {
      id: '/dashboard/mlops'
      path: '/mlops'
      fullPath: '/dashboard/mlops'
      preLoaderRoute: typeof DashboardMlopsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/geo': {
      id: '/dashboard/geo'
      path: '/geo'
      fullPath: '/dashboard/geo'
      preLoaderRoute: typeof DashboardGeoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/features': {
      id: '/dashboard/features'
      path: '/features'
      fullPath: '/dashboard/features'
      preLoaderRoute: typeof DashboardFeaturesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/detection': {
      id: '/dashboard/detection'
      path: '/detection'
      fullPath: '/dashboard/detection'
      preLoaderRoute: typeof DashboardDetectionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/capture': {
      id: '/dashboard/capture'
      path: '/capture'
      fullPath: '/dashboard/capture'
      preLoaderRoute: typeof DashboardCaptureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCaptureRoute: typeof DashboardCaptureRoute
  DashboardDetectionRoute: typeof DashboardDetectionRoute
  DashboardFeaturesRoute: typeof DashboardFeaturesRoute
  DashboardGeoRoute: typeof DashboardGeoRoute
  DashboardMlopsRoute: typeof DashboardMlopsRoute
  DashboardMonitoringRoute: typeof DashboardMonitoringRoute
  DashboardPredictionRoute: typeof DashboardPredictionRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCaptureRoute: DashboardCaptureRoute,
  DashboardDetectionRoute: DashboardDetectionRoute,
  DashboardFeaturesRoute: DashboardFeaturesRoute,
  DashboardGeoRoute: DashboardGeoRoute,
  DashboardMlopsRoute: DashboardMlopsRoute,
  DashboardMonitoringRoute: DashboardMonitoringRoute,
  DashboardPredictionRoute: DashboardPredictionRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
